name: Deploy BLAZOR APP USING SWA 

on:
  workflow_dispatch:  # This enables the manual trigger

jobs:
  build_and_deploy_job:    
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Set up .NET SDK (if you're using .NET for your project)
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/carl-randall/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES }}

       # Step 3: Install the wasm-tools workload
      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      # Step 4: Insert NuGet credentials
      - name: Setup NuGet config
        run: |
          sed -i 's/%NUGET_USERNAME%/${{ github.actor }}/g' nuget.config
          sed -i 's/%NUGET_TOKEN%/${{ secrets.GIT_PACKAGES }}/g' nuget.config

      # Step 5: Build and Deploy the app
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_CLIFF_04EC80F03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./Client" # App source code path
          api_location: "./Api" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
